services:
  myspot:
    build: ./app
    container_name: myspot
    restart: unless-stopped
    env_file:
      - .env
    networks: [traefik]
    labels:
      - traefik.enable=true
      - traefik.http.routers.myspot.rule=Host(`music.santiagoac.com`)
      - traefik.http.routers.myspot.entrypoints=websecure
      - traefik.http.routers.myspot.tls.certresolver=letsencrypt
      - traefik.http.services.myspot.loadbalancer.server.port=8000
    expose:
      - "8000"

networks:
  traefik:
    external: true
