services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    networks: [traefik]
    expose:
      - "2333"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ./lavalink/plugins:/opt/Lavalink/plugins

  myspot:
    build: ./app
    container_name: myspot
    restart: unless-stopped
    environment:
      - LAVA_URL=http://lavalink:2333
      - LAVA_PASS=youshallnotpass
    networks: [traefik]
    labels:
      - traefik.enable=true
      - traefik.http.routers.myspot.rule=Host(`music.santiagoac.com`)
      - traefik.http.routers.myspot.entrypoints=websecure
      - traefik.http.routers.myspot.tls.certresolver=letsencrypt
      - traefik.http.services.myspot.loadbalancer.server.port=8000

networks:
  traefik:
    external: true