server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true

plugins:
  # Plugin YouTube (nuevo) – necesario hoy
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.4"
    repository: "https://maven.lavalink.dev/releases"

  # LavaSrc: metadatos de Spotify/Apple/Deezer y resolución a YT u otras
  - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.7.2"
    repository: "https://maven.topi.wtf/releases"
